package com.example.main_page.model.currency_info

data class CurrencyInfoData(
    val AUD: CurrencyInfo,
    val BGN: CurrencyInfo,
    val BRL: CurrencyInfo,
    val CAD: CurrencyInfo,
    val CHF: CurrencyInfo,
    val CNY: CurrencyInfo,
    val CZK: CurrencyInfo,
    val DKK: CurrencyInfo,
    val EUR: CurrencyInfo,
    val GBR: CurrencyInfo,
    val HKD: CurrencyInfo,
    val HRK: CurrencyInfo,
    val HUF: CurrencyInfo,
    val IDR: CurrencyInfo,
    val ILS: CurrencyInfo,
    val INR: CurrencyInfo,
    val ISK: CurrencyInfo,
    val JPY: CurrencyInfo,
    val KRW: CurrencyInfo,
    val MXN: CurrencyInfo,
    val MYR: CurrencyInfo,
    val NOK: CurrencyInfo,
    val NZD: CurrencyInfo,
    val PHP: CurrencyInfo,
    val PLN: CurrencyInfo,
    val RON: CurrencyInfo,
    val RUB: CurrencyInfo,
    val SEK: CurrencyInfo,
    val SGD: CurrencyInfo,
    val THB: CurrencyInfo,
    val TRY: CurrencyInfo,
    val USD: CurrencyInfo,
    val ZAR: CurrencyInfo,
    val listCurrencyInfo: List<CurrencyInfo>
)
